# Generated by Django 3.2.6 on 2021-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexionbd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameconections', models.CharField(max_length=100, unique=True)),
                ('note', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('url', models.CharField(max_length=150)),
                ('password1', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tabla',
                'verbose_name_plural': 'Tablas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='datab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomtable', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('contrib', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
